### ISSUE TITLE
feat: Toast 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#13]
## 📌 작업 내용

[Chakra UI의 Toast](https://www.chakra-ui.com/docs/components/toast)를 사용

## ✅ To-Do

- [ ] Chakra UI 설치
- [ ] Toast 컴포넌트 생성 후 정상적으로 출력되는지 확인

## 📝 참고사항

\+ 1시간 +

담당하는 사람이 Chakra UI vs 직접 제작 중 뭐가 더 좋을지 판단 후 작성하기!!

**Comment by y0unj1NoH** [comment]
## 직접 제작 vs Chakra UI 후기
---
### 직접 제작
- 직접 구현해야 하는 부담
- 외부 라이브러리를 사용하지 않음 => 번들 크기↓, 초기 로딩 속도 빨라짐
- 직접 구현하여 다소 딱딱한 애니메이션 (고도화가 가능한 부분)
- 토스트를 info로만 단순 사용하기에는 적합

### Chakra UI
- 다양한 토스트 종류와 기능
- 애니메이션이 깔끔하고 부드러움
- 커스텀 용이
![image](https://github.com/user-attachments/assets/dab7ebfd-6f55-4f0c-9de9-8a1df0669b0d)
(그냥 원하는 스타일을 추가할 수 있습니다!)
- 일부 컴포넌트만 설치가 불가능하여 전체 라이브러리를 설치해야 하는 부담 => 번들 크기↑
![image](https://github.com/user-attachments/assets/65c2fae2-24f2-4d35-80e8-4546362f5511)
(설치하니까 스토리북에 어마무시하게 많은 컴포넌트가 생겼습니다... 지금 보는 사진의 5배 정도)
---
### 애니메이션 비교
1. 직접 구현
![Atoms _ Toast - Default ⋅ Storybook - Chrome 2024-11-24 23-14-22](https://github.com/user-attachments/assets/8780aae3-bf3d-4c1d-ae11-1e74bb51b614)

2. Chakra UI
![Atoms _ ToastChakra - Docs ⋅ Storybook - Chrome 2024-11-25 10-49-02](https://github.com/user-attachments/assets/6ea0e429-4512-4a8e-b9b8-9e658d7b6c12)
----
### 결론
- 미어켓 프로젝트는 **1. 토스트의 info만 사용해도 됨**, **2. 다른 UI는 직접 구현하기로 결정**했기 때문에 무거운 Chakra UI를 쓰는 건 투머치라고 생각됩니다.
- 하지만, 직접 구현한 부분에 대해서는 애니메이션을 보완하는 게 좋을 것 같아서 framer-motion으로 애니메이션 라이브러리를 따로 사용해서 수정하면 될 것 같습니다!
- Toast, Select를 라이브러리를 사용하려면 해당 컴포넌트 제공하는 라이브러리(toastify)를 쓰는 게 효율적일 것 같습니다.
- Chakra UI는 제공되는 컴포넌트들을 적극 사용할 때 쓰는 게 좋아 보입니다. 보다 보니깐 참 괜찮아보여서, 나중에 혼자 작업할 때나, 내공이 쌓인 뒤에 한번 경험해보는 것도 좋을 것 같습니다.

**Comment by y0unj1NoH** [comment]
# 토스트 디자인 시안 반영했습니다!
