### ISSUE TITLE
feat: TextDividerList 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#23]
## 📌 작업 내용

- Molecule의 TextDividerList 컴포넌트 개발

- 동네 선택 페이지의 근처 동네 위치 리스트
![Image](https://github.com/user-attachments/assets/f93aee7e-605a-435c-a6db-6f88f976c37c)

### props
- items: string[] 
- onClick: function

## ✅ To-Do

- [x] props로 전달 받은 items이 Divider와 함께 리스트 형태로 잘 뿌려지는지
- [x] Item들의 onClick이 잘 작동되는지 (Item들을 클릭 시 각 Item의 값이 console.log로 출력)

**Comment by ppyom** [comment]
@JW-Ahn0 @y0unj1NoH 

작업하던 중 해당 부분 논의가 필요할 것 같아 멘션했습니다.

1. Text에 onClick 추가해서 작업    ![Image](https://github.com/user-attachments/assets/191fc829-8218-4822-8b3e-1ad5577611fb)
    - 장점: 따로 적용된 스타일이 없어 상대적으로 자유롭게 스타일링 가능
    - 단점: Text에 onClick을 사용하지 않아도 onClick 존재 (영향이 가는지는 모름)
2. TextButton 사용
    ![Image](https://github.com/user-attachments/assets/5e098b9c-4883-4ae6-ab7b-e63f29b4884d)
    - 장점: onClick 별도로 추가하지 않아도 됨
    - 단점: 스타일이 이미 적용되어있음 (Button에 추가적으로 스타일이 적용된다면 문제 발생할지도?!)

만약 Text로 결정되면 Text에서 lint 걸리는 부분도 같이 수정해두겠습니다...!

**Comment by JW-Ahn0** [comment]
저는 TextButton의 단점 "스타일이 이미 적용되어있음 (Button에 추가적으로 스타일이 적용된다면 문제 발생할지도?!)"
 때문에 1안으로 가는게 좋은 것 같습니다. Text에 div 감싸고 거기에 onClick 주는 방식이 좋은 것 같습니다!

**Comment by y0unj1NoH** [comment]
저도 아토믹 짤 때 맨 처음 생각한 건 전자여서, 1안으로 가는 거 좋은 것 같습니다!
