### ISSUE TITLE
study: 컴파운드 패턴 공부하기

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#29]
## 📌 작업 내용

https://patterns-dev-kr.github.io/design-patterns/compound-pattern/

## ✅ To-Do

- [ ] 컴파운트 패턴 공부 후 이슈에 기록하기(자신만의 언어로 )

**Comment by ppyom** [comment]
@JW-Ahn0 @y0unj1NoH

**Comment by JW-Ahn0** [comment]
TODO (아래 질문에 답할 수 있어야 될 것 같습니다.)

- 1. 컴파운드 패턴과 Context API 는 동일한가?
- 2. 다르다면 어떤 부분에서 다른 가?

- 3. 컴파운드 패턴만 사용하는 경우의 예시
- 3-1. 왜 컴파운드 패턴만 적용하는가? (=컴파운드 패턴만 사용해서 얻을 수 있는 효과는?)

- 4. Context API 만 적용하는 경우의 예시
- 4-1. 왜 Context API만 적용하는가? (=Context API만 사용해서 얻을 수 있는 효과는?)

- 5. 컴파운드 패턴 && Context API 함께 쓰는 경우의 예시
- 5-1 왜 둘을 함께 사용하는가? (=둘을 함께 사용해서 얻을 수 있는 효과는?)

**Comment by y0unj1NoH** [comment]
https://www.notion.so/Compound-Pattern-146656fbc8d580cf875fe90fc958bb53?pvs=4

**Comment by ppyom** [comment]
## 시작 전 준우님 작성해주신 글

- 컴파운드 패턴이란 무엇인가요?
    - 여러 컴포넌트들이 모여 하나의 **동작**을 할 수 있게 만드는 패턴
    - 일반적으로 Context 생성 → 부모 컴포넌트 작성 → 자식 컴포넌트 작성 → 부모와 자식 연결 순서로 진행
- 컴파운드 패턴과 Context API 는 동일한가?
    - 동일하지 않습니다.
        
        컴파운드 패턴은 ContextAPI를 함께 사용해 부모(최상위)요소의 상태를 자식 요소에서 쉽게 사용하는 방식으로 ContextAPI를 많이 사용하는 것 뿐입니다.
        
- 3 컴파운드 패턴만 사용하는 경우의 예시
    - Select `<select>{children}</select>`
        - Select.Option `<option value={value}>{value}</option>
- 3-1 왜 컴파운드 패턴만 적용하는가? (=컴파운드 패턴만 사용해서 얻을 수 있는 효과는?) => 모르겠습니다.
- Context API 만 적용하는 경우의 예시
    - List 컴포넌트
- 왜 Context API만 적용하는가? (=Context API만 사용해서 얻을 수 있는 효과는?)
    - Context 내부에서 생성 / 삭제 등의 method를 Item 컴포넌트에서도 불러올 수 있습니다.
- 컴파운드 패턴 && Context API 함께 쓰는 경우의 예시
    - Modal
        - Modal.Header
        - Modal.Body
        - Modal.Footer
- 왜 둘을 함께 사용하는가? (=둘을 함께 사용해서 얻을 수 있는 효과는?)
    - 상위 컴포넌트에서 isOpen, setOpen 등을 관리하고, 그걸 하위 자식에 전달하지 않고 useContext를 호출해 불러와 사용하는 방식이라 하위 컴포넌트를 깔끔하게 (필요한 Props만 넣어서) 관리할 수 있습니다.

# Compound 패턴

우선 찾아보다보니 제가 생각하던것은 살짝 다른 것 같습니다………

제가 생각했던 느낌은

1. 각각 다른 컴포넌트 생성 (예를들면 DefaultButton, TextButton, IconButton, …)
2. 호출할 때 `Button` 또는 `Button.Text` 또는 `Button.Icon`처럼 호출

이런 느낌이었습니다…

이것도 컴파운드 패턴으로 말할 수 있는지는 찾아봐야할 것 같습니다.

## Compound 패턴

Compound는 위에서 제가 막 작성한 느낌보다는 내부에서 뭔가 **“동작”** 에 중점이 맞춰진 느낌이 살짝 보입니다!!

## ContextAPI와 함께 사용하는 이유는?

Context API를 사용하면 Provider 하위에 있는 컴포넌트들이 내가 내려주는 value를 어느 곳이든 사용할 수 있기 때문에 함께 사용합니다.

Context에서 뭔가 상태를 가지고 있고, 그 상태를 사용해 하위 컴포넌트가 사용할 때 유용하게 사용될 것 같습니다. 

## 크몽을 다시 읽어보면서 든 생각??

크몽 CompoundPattern 글을 읽었을 때 “***아토믹 디자인 적용과 동시에 Context API 를 활용하여 컴파운드 패턴 또한 적용시켰기 때문에...***" 라는 말을 보고 자세히 읽어보니 `Atom.Label` 와 같은 형태로 사용하는 것을 봤습니다.

크몽의 폴더 구조를 보니 컴포넌트에서 atom을 쪼개고, 쪼개진 atom을 조합하는 방식으로 만들었기 때문에 해당 컴포넌트(GigCard)의 atom에 useCardContext가 들어갈 수 있어 자유로운 디자인이 만들어질 수 있었다라고 생각합니다.

## 참고한 글

- [정백경, Medium, 전국 각지 지구촌 구석구석에 계신 React 개발자님들! 코드에 디자인 시스템을 찍어 드셔보세요 [아토믹 컴파운드 패턴 적용기]](https://blog.kmong.com/react%EB%A1%9C-%ED%99%95%EC%9E%A5%EC%84%B1-%EC%9E%88%EA%B3%A0-%EC%9E%AC%EC%82%AC%EC%9A%A9%EC%84%B1%EB%8F%84-%EC%9E%88%EA%B3%A0-%EA%B0%80%EB%8F%85%EC%84%B1%EB%8F%84-%EC%9E%88%EC%9C%BC%EB%A9%B4%EC%84%9C-%EC%BD%94%EB%93%9C%EB%A5%BC-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0%EB%8F%84-%EC%89%BD%EA%B3%A0-%EB%8F%99%EC%8B%9C%EC%97%90-%EC%A0%9C%EA%B1%B0%ED%95%98%EA%B8%B0-%EC%89%AC%EC%9A%B4-%EC%BD%94%EB%93%9C-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-%EC%95%84%ED%86%A0%EB%AF%B9-%EC%BB%B4%ED%8C%8C%EC%9A%B4%EB%93%9C-%ED%8C%A8%ED%84%B4-7912f1b65a40)
- [patterns, Compound 패턴](https://patterns-dev-kr.github.io/design-patterns/compound-pattern/)
- [Youngjo Gil, velog, [React] Namespace Component](https://velog.io/@0jo-gil/Namespace-Component)

**Comment by y0unj1NoH** [comment]
## Compound pattern를 어떻게 사용할 것인가?
1. 전부 다 나열 후 템플릿에서 바로 사용 (우디: https://geekk89.medium.com/react-compound-component-%ED%8C%A8%ED%84%B4-b1fcb7128d7b)
2. 합파일(각 organism)에서 네임스페이스 형태로 한 번 더 묶기
3. type으로 props로 정하고 하나로 쓰자 (우려되는 부분: 순서에 따라 모든 경우를 타입으로 줘야 하나?)
