### ISSUE TITLE
feat: PostImageItem 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#31]
## 📌 작업 내용

- x 버튼 눌러서 onClick 이벤트 출력 
- isThumbnail 로 대표 사진 구분이 가능

![Image](https://github.com/user-attachments/assets/e074d52e-317b-44a9-9cee-27e247204941)

### props
- imgUrl: string
- onClick: function
- isThumbnail: boolean

## ✅ To-Do

- [x] 이미지가 잘 나오는지
- [x] onClick으로 console.log가 잘 찍히는지
- [x] isThumbnail이 true일 때 대표 사진으로 잘 반영되는지

## 📝 참고사항
- 첫 번째 사진을 대표 사진으로 지정

**Comment by JW-Ahn0** [comment]
참고사항의 
'첫 번째 사진을 대표 사진으로 지정' 는 여기서는 적절하지 않은 표현인 것 같습니다.

별도로 'PostImageIList' 컴포넌트 개발하고 거기서 첫 번째 사진을 대표 사진을 지정 (map으로 돌면서 첫 번째 인덱스에 isThumbnail 값을 true로 주는 형태) 가 맞을 것 같네요.
