### ISSUE TITLE
feat: PostItem 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#64]
## 📌 작업 내용

**!! 논의 필요  !!**

PostItem 

| Mini  | Default | Seller | Buyer |
| -- | -- | -- | -- |
| ![Image](https://github.com/user-attachments/assets/dbe5475b-76f1-48c3-b4ba-8c582c1f8c29) | ![Image](https://github.com/user-attachments/assets/0efc7937-96c7-4812-ac7e-1fb9c2d99849) | ![Image](https://github.com/user-attachments/assets/3e3fd4d1-37e9-4180-b5d8-6934b081dd8e) | ![Image](https://github.com/user-attachments/assets/3d7539a1-da0b-48d5-85cf-86786ea076b8) |

어디까지 세세하게 컴파운드 패턴으로 분리할 것인가는 개발하는 개인에게 맡깁니다.
1. mini default seller 이렇게 3개의 타입으로 나눠도 되고
2. image, title, desc, 가격.. 등등 해서 6개까지로 나눠도 됩니다. 

#### Default

- productId: number
- image: string
- title: string
- address: string location
- minPrice: number 최소 입찰가
- maxPrice: number 최종 입찰가 (최고 입찰가 / 나의 입찰가)
- uploadTime: number 시작시간 -> n분 전 계산
- expiredTime: number 마감시간 -> 남은 시간 계산
- isEarly: boolean 조기종료

#### Mini

- image: string
- title: string
- maxPrice: number 최종 입찰가

## ✅ To-Do

- [ ]
- [ ]

## 📝 참고사항

컴파운드 패턴으로 작업

### 선행 조건

- #29
- #3 
- #9 
- #12 
- #15 
-

**Comment by ppyom** [comment]
# 컴파운드 패턴 분리

## PostItem(Root)

### props

- onClick: () => void

## .Image

### props

- imgUrl?: string
- size?: "default" | "mini"

## .Title

### props

- title: string

## .LocationAndTime

### props

- address: string
- uploadTime: string

## .Price

00,000원

### props

- price: number
- title?: string

## .RemainingTime

### props

- expiredTime: string

## .ButtonContainer

### props

- buttonText: string
- onTextButtonClick: () => void;
- icon?: IconType
- onIconButtonClick?: () => void;

**Comment by ppyom** [comment]
# Story

## Default

넣을 수 있는거 전부

![Image](https://github.com/user-attachments/assets/f40887d5-6e6a-4805-834e-963874bc5eab)

**Comment by JW-Ahn0** [comment]
디자인 작업 중입니다.
