### ISSUE TITLE
feat: MenuBottomSheet 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#72]
## 📌 작업 내용

![Image](https://github.com/user-attachments/assets/a46c17c8-811a-4b2d-b82f-7a61c3543a7f)

### props

- menus: Menu[]

## ✅ To-Do

- [ ] 각 메뉴 클릭 시 onClick 이벤트 잘 실행되는지

## 📝 참고사항

- Menu
  - title: string
  - onClick: () => void

### 선행 조건

- #12 
- #69

**Comment by ppyom** [comment]
# 아마도 이런느낌??

```tsx
<ModalBottomSheet open={open} onClose={onClose}>
  {buttons.map(({ title, onClick }, idx) => <TextButton key={`bottom_menu_${idx}`} text={title} onClick={onClick} />)}
</ModalBottomSheet>
```
