### ISSUE TITLE
feat: AuctionBidBottomSheet 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#73]
## 📌 작업 내용

![Image](https://github.com/user-attachments/assets/8107703a-528a-44de-8ce7-a408c4b4d970)

### props

- price: number => 이미 입찰을 진행한 구매자의 경우 가격이 이미 있을지도!!
- setPrice: (price: number) => void
- onBid: () => void

## ✅ To-Do

- [ ] 입력된 가격이 입찰하기 버튼을 눌렀을 때 console에 출력되는지

### 선행 조건

- #69

**Comment by ppyom** [comment]
# 고민

어차피 같이 사용될텐데 AuctionControlBar의 z-index를 맨 위로 올려서 입찰하기 버튼의 onClick만 변경할지??

**Comment by ppyom** [comment]
# 어떤식으로 만들까

```tsx
<ModalBottomSheet open={open} onClose={onClose}>
  <Text content="희망 입찰가" />
  <Input price={price} setPrice={setPrice} placeholder={beforePrice || minPrice} />
  <TextButton text="입찰하기" onClick={onBid} />
</ModalBottomSheet>
```

## props

- open, onClose => 상속
- price, setPrice => (상위에서 넘겨주는) 가격 state
- beforePrice => (이전에 입찰한 경우) 나의 이전 입찰가
- minPrice => 최소 입찰가
- onBid => 입찰 실행 시 실행될 함수
